POST https://www.skiparadies24.de/api/product-visibility?_response=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJhZG1pbmlzdHJhdGlvbiIsImp0aSI6IjZlOWVkYjljMDk0YjBiZjU4YTNhYmUxYjgxZjg1YzRiMGYyYzI2ZTA0YjJjOTljYmE2MWVkYWI2ZjFiMjdjYzY0NWJmM2NjNmY5YWM1NDY0IiwiaWF0IjoxNjk4NzU5NDc5LjU0MDA0NywibmJmIjoxNjk4NzU5NDc5LjU0MDA0OSwiZXhwIjoxNjk4NzYwMDc5LjUzNzYwOSwic3ViIjoiMDE4YjY2OTFiYWM4NzE0N2I3MmU1MzU4ZDZjOTc3MzIiLCJzY29wZXMiOlsid3JpdGUiLCJhZG1pbiJdfQ.bg44pKpwOyqPmswkCdyFQ8ecMAmocXWoXjC_t08IeWjIuely90oymHTEZTVSwVl30B3NM1heEH0bA_yWkQYy9lblHCAyz2GK-flM2uzXNkywIvmrbi67JoVJShM9C6UEcMAqzwG4qJrvFeZg-dxy5D1KdtFgqcc1bbAikcq62CzEAW8qczIH5i53o4gnMtYPmRMb4rqFPLcPh4odHiM1uAi57i3Kjl0UJFdvOskiBWHBJG9xym5xP1yL_D1Xx3OtdaybKNN-f3OVyNDyjLcQ9PK2BpHgtdhq4Sm5CjnaMM38ctd_Hf6VWEwWrunyz12oOf68g6QQyueKjyKAgMDJFA

{
  "productId": "60ca873f19cae6c2c281ae4b9081f55c",
  "salesChannelId": "018b6691babd709aa2d1189f1924c4d9",
  "visibility": 1
}